[package]
name = "frontend"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
# internal
model = { workspace = true, features = ["wasm"] }
radix = { workspace = true }

# 3rd party
chrono = { workspace = true }
console_error_panic_hook = { workspace = true }
js-sys = { workspace = true }
leptos = { workspace = true, features = ["csr"] }
leptos-struct-table = { workspace = true, features = ["uuid", "chrono"] }
reactive_graph = { workspace = true }
reactive_stores = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde-wasm-bindgen = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = [
    "macros",
    "std",
    "formatting",
    "wasm-bindgen",
    "serde",
] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
leptos_router = "0.8.11"
leptos_router_macro = "0.8.6"
itertools = "0.14.0"

[lib]
crate-type = ["cdylib", "rlib"]
